% Clean workspace
clear all; close all; clc

load subdata.mat

L = 10; % spatial domain
n = 64; % Fourier modes

x2 = linspace(-L,L,n+1); x = x2(1:n); y = x; z = x;
k = (2*pi/(2*L))*[0:(n/2 - 1) -n/2:-1]; 
ks = fftshift(k); 
[X,Y,Z]=meshgrid(x,y,z);
[Kx,Ky,Kz]=meshgrid(ks,ks,ks);

% 1、Through averaging of the spectrum, 
% determine the frequency signature (center frequency) generated by the submarine.

Uave = zeros(n,n,n);

for j=1:49
    Un(:,:,:)=reshape(subdata(:,j),n,n,n);
    Un = fftn(Un);
    Uave = Uave + Un;
    
    % close all, isosurface(X,Y,Z,abs(Un)/M,0.7)
    % axis([-20 20 -20 20 -20 20]), grid on, drawnow
    % pause(1) 
end

Uave = abs(fftshift(Uave))/49;
M = max(abs(Uave),[],'all');
close all, 
figure(1)
isosurface(Kx,Ky,Kz,abs(Uave)/M,0.7)
grid on, drawnow
title('Average Frequency during 25 Hours')
xlabel('X axis'), ylabel('Y axis'), zlabel('Z axis')

%% Q2
% 2. Filter the data around the center frequency determined above 
%    in order to denoise the data and determine the path of the submarine. 
tau = 0.5;
gx = exp(-tau*(Kx-4.5).^2);
gy = exp(-tau*(Ky+7).^2);
gz = exp(-tau*(Kz-3).^2);
path = zeros(3,49);
for j = 1:49
    Un(:,:,:)=reshape(subdata(:,j),n,n,n);
    Uf = gx.*gy.*gz.*fftshift(fftn(Un));
    Ut = ifftn(Uf);
    [mxv,idx] = max(abs(Ut(:)));
    path(1,j) = X(idx);
    path(2,j) = Y(idx);
    path(3,j) = Z(idx);
end
figure(2)
plot3(path(1,:),path(2,:),path(3,:));
title('Path of the Submarine based on the denoised data')
xlabel('X axis'), ylabel('Y axis'), zlabel('Z axis')

%% Q3
% Where should you send your P-8 Poseidon subtracking aircraft? 
% Give the x and y coordinates in a table to follow the submarine.

xy_coordinates = path(1:2,:);
final_p = xy_coordinates(:,end)


